CRITICAL - 2022-12-03 01:12:29 --> Call to a member function get() on string
in APPPATH\Controllers\Admin.php on line 66.
 1 SYSTEMPATH\CodeIgniter.php(902): App\Controllers\Admin->save()
 2 SYSTEMPATH\CodeIgniter.php(457): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Admin))
 3 SYSTEMPATH\CodeIgniter.php(340): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 4 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
 5 SYSTEMPATH\Commands\Server\rewrite.php(46): require_once('FCPATH\\index.php')
CRITICAL - 2022-12-03 01:19:38 --> Call to a member function getWhere() on string
in APPPATH\Controllers\Admin.php on line 69.
 1 SYSTEMPATH\CodeIgniter.php(902): App\Controllers\Admin->save()
 2 SYSTEMPATH\CodeIgniter.php(457): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Admin))
 3 SYSTEMPATH\CodeIgniter.php(340): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 4 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
 5 SYSTEMPATH\Commands\Server\rewrite.php(46): require_once('FCPATH\\index.php')
CRITICAL - 2022-12-03 01:24:40 --> Object of class CodeIgniter\Database\MySQLi\Builder could not be converted to string
in SYSTEMPATH\Database\Query.php on line 335.
 1 SYSTEMPATH\Database\Query.php(335): strtr('INSERT INTO `users` (`username`, `fullname`, `no_telp`, `email`, `jk`, `kamar`, `thn_masuk`, `wali`, `no_wali`, `password_hash`, `created_at`) VALUES (:username:, :fullname:, :no_telp:, :email:, :jk:, :kamar:, :thn_masuk:, :wali:, :no_wali:, :password_hash:, :created_at:)', [...])
 2 SYSTEMPATH\Database\Query.php(310): CodeIgniter\Database\Query->matchNamedBinds('INSERT INTO `users` (`username`, `fullname`, `no_telp`, `email`, `jk`, `kamar`, `thn_masuk`, `wali`, `no_wali`, `password_hash`, `created_at`) VALUES (:username:, :fullname:, :no_telp:, :email:, :jk:, :kamar:, :thn_masuk:, :wali:, :no_wali:, :password_hash:, :created_at:)', [...])
 3 SYSTEMPATH\Database\Query.php(159): CodeIgniter\Database\Query->compileBinds()
 4 SYSTEMPATH\Database\BaseConnection.php(620): CodeIgniter\Database\Query->getQuery()
 5 SYSTEMPATH\Database\BaseBuilder.php(1916): CodeIgniter\Database\BaseConnection->query('INSERT INTO `users` (`username`, `fullname`, `no_telp`, `email`, `jk`, `kamar`, `thn_masuk`, `wali`, `no_wali`, `password_hash`, `created_at`) VALUES (:username:, :fullname:, :no_telp:, :email:, :jk:, :kamar:, :thn_masuk:, :wali:, :no_wali:, :password_hash:, :created_at:)', [...], false)
 6 APPPATH\Controllers\Admin.php(89): CodeIgniter\Database\BaseBuilder->insert([...])
 7 SYSTEMPATH\CodeIgniter.php(902): App\Controllers\Admin->save()
 8 SYSTEMPATH\CodeIgniter.php(457): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Admin))
 9 SYSTEMPATH\CodeIgniter.php(340): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
10 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
11 SYSTEMPATH\Commands\Server\rewrite.php(46): require_once('FCPATH\\index.php')
CRITICAL - 2022-12-03 01:26:39 --> Call to a member function table() on string
in APPPATH\Controllers\Admin.php on line 70.
 1 SYSTEMPATH\CodeIgniter.php(902): App\Controllers\Admin->save()
 2 SYSTEMPATH\CodeIgniter.php(457): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Admin))
 3 SYSTEMPATH\CodeIgniter.php(340): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 4 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
 5 SYSTEMPATH\Commands\Server\rewrite.php(46): require_once('FCPATH\\index.php')
CRITICAL - 2022-12-03 01:27:29 --> Call to a member function table() on string
in APPPATH\Controllers\Admin.php on line 70.
 1 SYSTEMPATH\CodeIgniter.php(902): App\Controllers\Admin->save()
 2 SYSTEMPATH\CodeIgniter.php(457): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Admin))
 3 SYSTEMPATH\CodeIgniter.php(340): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 4 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
 5 SYSTEMPATH\Commands\Server\rewrite.php(46): require_once('FCPATH\\index.php')
CRITICAL - 2022-12-03 01:28:18 --> Call to a member function table() on string
in APPPATH\Controllers\Admin.php on line 70.
 1 SYSTEMPATH\CodeIgniter.php(902): App\Controllers\Admin->save()
 2 SYSTEMPATH\CodeIgniter.php(457): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Admin))
 3 SYSTEMPATH\CodeIgniter.php(340): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 4 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
 5 SYSTEMPATH\Commands\Server\rewrite.php(46): require_once('FCPATH\\index.php')
CRITICAL - 2022-12-03 01:29:18 --> Call to a member function table() on string
in APPPATH\Controllers\Admin.php on line 70.
 1 SYSTEMPATH\CodeIgniter.php(902): App\Controllers\Admin->save()
 2 SYSTEMPATH\CodeIgniter.php(457): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Admin))
 3 SYSTEMPATH\CodeIgniter.php(340): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 4 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
 5 SYSTEMPATH\Commands\Server\rewrite.php(46): require_once('FCPATH\\index.php')
ERROR - 2022-12-03 01:42:15 --> mysqli_sql_exception: Unknown column 'gender.id_gender' in 'field list' in C:\xampp\htdocs\tugas_akhir\vendor\codeigniter4\framework\system\Database\MySQLi\Connection.php:292
Stack trace:
#0 C:\xampp\htdocs\tugas_akhir\vendor\codeigniter4\framework\system\Database\MySQLi\Connection.php(292): mysqli->query('SELECT `gender`...', 0)
#1 C:\xampp\htdocs\tugas_akhir\vendor\codeigniter4\framework\system\Database\BaseConnection.php(693): CodeIgniter\Database\MySQLi\Connection->execute('SELECT `gender`...')
#2 C:\xampp\htdocs\tugas_akhir\vendor\codeigniter4\framework\system\Database\BaseConnection.php(620): CodeIgniter\Database\BaseConnection->simpleQuery('SELECT `gender`...')
#3 C:\xampp\htdocs\tugas_akhir\vendor\codeigniter4\framework\system\Database\BaseBuilder.php(1585): CodeIgniter\Database\BaseConnection->query('SELECT `gender`...', Array, false)
#4 C:\xampp\htdocs\tugas_akhir\app\Controllers\Admin.php(72): CodeIgniter\Database\BaseBuilder->get()
#5 C:\xampp\htdocs\tugas_akhir\vendor\codeigniter4\framework\system\CodeIgniter.php(902): App\Controllers\Admin->save()
#6 C:\xampp\htdocs\tugas_akhir\vendor\codeigniter4\framework\system\CodeIgniter.php(457): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Admin))
#7 C:\xampp\htdocs\tugas_akhir\vendor\codeigniter4\framework\system\CodeIgniter.php(340): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#8 C:\xampp\htdocs\tugas_akhir\public\index.php(67): CodeIgniter\CodeIgniter->run()
#9 C:\xampp\htdocs\tugas_akhir\vendor\codeigniter4\framework\system\Commands\Server\rewrite.php(46): require_once('C:\\xampp\\htdocs...')
#10 {main}
CRITICAL - 2022-12-03 01:42:15 --> Unknown column 'gender.id_gender' in 'field list'
in SYSTEMPATH\Database\MySQLi\Connection.php on line 292.
 1 SYSTEMPATH\Database\MySQLi\Connection.php(292): mysqli->query('SELECT `gender`.`id_gender` as `idgender`, `sex`, `nama_kamar`, `id_kamar`
FROM `users`
JOIN `kamar_santri` ON `kamar_santri`.`gender_id` = `id_gender`
WHERE `id_gender` = \'1\'', 0)
 2 SYSTEMPATH\Database\BaseConnection.php(693): CodeIgniter\Database\MySQLi\Connection->execute('SELECT `gender`.`id_gender` as `idgender`, `sex`, `nama_kamar`, `id_kamar`
FROM `users`
JOIN `kamar_santri` ON `kamar_santri`.`gender_id` = `id_gender`
WHERE `id_gender` = \'1\'')
 3 SYSTEMPATH\Database\BaseConnection.php(620): CodeIgniter\Database\BaseConnection->simpleQuery('SELECT `gender`.`id_gender` as `idgender`, `sex`, `nama_kamar`, `id_kamar`
FROM `users`
JOIN `kamar_santri` ON `kamar_santri`.`gender_id` = `id_gender`
WHERE `id_gender` = \'1\'')
 4 SYSTEMPATH\Database\BaseBuilder.php(1585): CodeIgniter\Database\BaseConnection->query('SELECT `gender`.`id_gender` as `idgender`, `sex`, `nama_kamar`, `id_kamar`
FROM `users`
JOIN `kamar_santri` ON `kamar_santri`.`gender_id` = `id_gender`
WHERE `id_gender` = :id_gender:', [...], false)
 5 APPPATH\Controllers\Admin.php(72): CodeIgniter\Database\BaseBuilder->get()
 6 SYSTEMPATH\CodeIgniter.php(902): App\Controllers\Admin->save()
 7 SYSTEMPATH\CodeIgniter.php(457): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Admin))
 8 SYSTEMPATH\CodeIgniter.php(340): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 9 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
10 SYSTEMPATH\Commands\Server\rewrite.php(46): require_once('FCPATH\\index.php')
CRITICAL - 2022-12-03 01:43:18 --> Object of class CodeIgniter\Database\MySQLi\Result could not be converted to string
in SYSTEMPATH\Database\Query.php on line 335.
 1 SYSTEMPATH\Database\Query.php(335): strtr('INSERT INTO `users` (`username`, `fullname`, `no_telp`, `email`, `jk`, `kamar`, `thn_masuk`, `wali`, `no_wali`, `password_hash`, `created_at`) VALUES (:username:, :fullname:, :no_telp:, :email:, :jk:, :kamar:, :thn_masuk:, :wali:, :no_wali:, :password_hash:, :created_at:)', [...])
 2 SYSTEMPATH\Database\Query.php(310): CodeIgniter\Database\Query->matchNamedBinds('INSERT INTO `users` (`username`, `fullname`, `no_telp`, `email`, `jk`, `kamar`, `thn_masuk`, `wali`, `no_wali`, `password_hash`, `created_at`) VALUES (:username:, :fullname:, :no_telp:, :email:, :jk:, :kamar:, :thn_masuk:, :wali:, :no_wali:, :password_hash:, :created_at:)', [...])
 3 SYSTEMPATH\Database\Query.php(159): CodeIgniter\Database\Query->compileBinds()
 4 SYSTEMPATH\Database\BaseConnection.php(620): CodeIgniter\Database\Query->getQuery()
 5 SYSTEMPATH\Database\BaseBuilder.php(1916): CodeIgniter\Database\BaseConnection->query('INSERT INTO `users` (`username`, `fullname`, `no_telp`, `email`, `jk`, `kamar`, `thn_masuk`, `wali`, `no_wali`, `password_hash`, `created_at`) VALUES (:username:, :fullname:, :no_telp:, :email:, :jk:, :kamar:, :thn_masuk:, :wali:, :no_wali:, :password_hash:, :created_at:)', [...], false)
 6 APPPATH\Controllers\Admin.php(87): CodeIgniter\Database\BaseBuilder->insert([...])
 7 SYSTEMPATH\CodeIgniter.php(902): App\Controllers\Admin->save()
 8 SYSTEMPATH\CodeIgniter.php(457): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Admin))
 9 SYSTEMPATH\CodeIgniter.php(340): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
10 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
11 SYSTEMPATH\Commands\Server\rewrite.php(46): require_once('FCPATH\\index.php')
CRITICAL - 2022-12-03 02:41:15 --> Object of class CodeIgniter\Database\MySQLi\Result could not be converted to string
in SYSTEMPATH\Database\Query.php on line 335.
 1 SYSTEMPATH\Database\Query.php(335): strtr('INSERT INTO `users` (`username`, `fullname`, `no_telp`, `email`, `jk`, `kamar`, `thn_masuk`, `wali`, `no_wali`, `password_hash`, `created_at`) VALUES (:username:, :fullname:, :no_telp:, :email:, :jk:, :kamar:, :thn_masuk:, :wali:, :no_wali:, :password_hash:, :created_at:)', [...])
 2 SYSTEMPATH\Database\Query.php(310): CodeIgniter\Database\Query->matchNamedBinds('INSERT INTO `users` (`username`, `fullname`, `no_telp`, `email`, `jk`, `kamar`, `thn_masuk`, `wali`, `no_wali`, `password_hash`, `created_at`) VALUES (:username:, :fullname:, :no_telp:, :email:, :jk:, :kamar:, :thn_masuk:, :wali:, :no_wali:, :password_hash:, :created_at:)', [...])
 3 SYSTEMPATH\Database\Query.php(159): CodeIgniter\Database\Query->compileBinds()
 4 SYSTEMPATH\Database\BaseConnection.php(620): CodeIgniter\Database\Query->getQuery()
 5 SYSTEMPATH\Database\BaseBuilder.php(1916): CodeIgniter\Database\BaseConnection->query('INSERT INTO `users` (`username`, `fullname`, `no_telp`, `email`, `jk`, `kamar`, `thn_masuk`, `wali`, `no_wali`, `password_hash`, `created_at`) VALUES (:username:, :fullname:, :no_telp:, :email:, :jk:, :kamar:, :thn_masuk:, :wali:, :no_wali:, :password_hash:, :created_at:)', [...], false)
 6 APPPATH\Controllers\Admin.php(87): CodeIgniter\Database\BaseBuilder->insert([...])
 7 SYSTEMPATH\CodeIgniter.php(902): App\Controllers\Admin->save()
 8 SYSTEMPATH\CodeIgniter.php(457): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Admin))
 9 SYSTEMPATH\CodeIgniter.php(340): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
10 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
11 SYSTEMPATH\Commands\Server\rewrite.php(46): require_once('FCPATH\\index.php')
CRITICAL - 2022-12-03 02:41:30 --> Object of class CodeIgniter\Database\MySQLi\Result could not be converted to string
in SYSTEMPATH\Database\Query.php on line 335.
 1 SYSTEMPATH\Database\Query.php(335): strtr('INSERT INTO `users` (`username`, `fullname`, `no_telp`, `email`, `jk`, `kamar`, `thn_masuk`, `wali`, `no_wali`, `password_hash`, `created_at`) VALUES (:username:, :fullname:, :no_telp:, :email:, :jk:, :kamar:, :thn_masuk:, :wali:, :no_wali:, :password_hash:, :created_at:)', [...])
 2 SYSTEMPATH\Database\Query.php(310): CodeIgniter\Database\Query->matchNamedBinds('INSERT INTO `users` (`username`, `fullname`, `no_telp`, `email`, `jk`, `kamar`, `thn_masuk`, `wali`, `no_wali`, `password_hash`, `created_at`) VALUES (:username:, :fullname:, :no_telp:, :email:, :jk:, :kamar:, :thn_masuk:, :wali:, :no_wali:, :password_hash:, :created_at:)', [...])
 3 SYSTEMPATH\Database\Query.php(159): CodeIgniter\Database\Query->compileBinds()
 4 SYSTEMPATH\Database\BaseConnection.php(620): CodeIgniter\Database\Query->getQuery()
 5 SYSTEMPATH\Database\BaseBuilder.php(1916): CodeIgniter\Database\BaseConnection->query('INSERT INTO `users` (`username`, `fullname`, `no_telp`, `email`, `jk`, `kamar`, `thn_masuk`, `wali`, `no_wali`, `password_hash`, `created_at`) VALUES (:username:, :fullname:, :no_telp:, :email:, :jk:, :kamar:, :thn_masuk:, :wali:, :no_wali:, :password_hash:, :created_at:)', [...], false)
 6 APPPATH\Controllers\Admin.php(87): CodeIgniter\Database\BaseBuilder->insert([...])
 7 SYSTEMPATH\CodeIgniter.php(902): App\Controllers\Admin->save()
 8 SYSTEMPATH\CodeIgniter.php(457): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Admin))
 9 SYSTEMPATH\CodeIgniter.php(340): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
10 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
11 SYSTEMPATH\Commands\Server\rewrite.php(46): require_once('FCPATH\\index.php')
CRITICAL - 2022-12-03 02:42:43 --> Undefined variable: jk
in APPPATH\Controllers\Admin.php on line 73.
 1 APPPATH\Controllers\Admin.php(73): CodeIgniter\Debug\Exceptions->errorHandler(8, 'Undefined variable: jk', 'APPPATH\\Controllers\\Admin.php', 73, [...])
 2 SYSTEMPATH\CodeIgniter.php(902): App\Controllers\Admin->save()
 3 SYSTEMPATH\CodeIgniter.php(457): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Admin))
 4 SYSTEMPATH\CodeIgniter.php(340): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 5 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
 6 SYSTEMPATH\Commands\Server\rewrite.php(46): require_once('FCPATH\\index.php')
ERROR - 2022-12-03 02:43:49 --> mysqli_sql_exception: Unknown column 'idgender' in 'where clause' in C:\xampp\htdocs\tugas_akhir\vendor\codeigniter4\framework\system\Database\MySQLi\Connection.php:292
Stack trace:
#0 C:\xampp\htdocs\tugas_akhir\vendor\codeigniter4\framework\system\Database\MySQLi\Connection.php(292): mysqli->query('SELECT `gender`...', 0)
#1 C:\xampp\htdocs\tugas_akhir\vendor\codeigniter4\framework\system\Database\BaseConnection.php(693): CodeIgniter\Database\MySQLi\Connection->execute('SELECT `gender`...')
#2 C:\xampp\htdocs\tugas_akhir\vendor\codeigniter4\framework\system\Database\BaseConnection.php(620): CodeIgniter\Database\BaseConnection->simpleQuery('SELECT `gender`...')
#3 C:\xampp\htdocs\tugas_akhir\vendor\codeigniter4\framework\system\Database\BaseBuilder.php(1585): CodeIgniter\Database\BaseConnection->query('SELECT `gender`...', Array, false)
#4 C:\xampp\htdocs\tugas_akhir\app\Controllers\Admin.php(72): CodeIgniter\Database\BaseBuilder->get()
#5 C:\xampp\htdocs\tugas_akhir\vendor\codeigniter4\framework\system\CodeIgniter.php(902): App\Controllers\Admin->save()
#6 C:\xampp\htdocs\tugas_akhir\vendor\codeigniter4\framework\system\CodeIgniter.php(457): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Admin))
#7 C:\xampp\htdocs\tugas_akhir\vendor\codeigniter4\framework\system\CodeIgniter.php(340): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#8 C:\xampp\htdocs\tugas_akhir\public\index.php(67): CodeIgniter\CodeIgniter->run()
#9 C:\xampp\htdocs\tugas_akhir\vendor\codeigniter4\framework\system\Commands\Server\rewrite.php(46): require_once('C:\\xampp\\htdocs...')
#10 {main}
CRITICAL - 2022-12-03 02:43:49 --> Unknown column 'idgender' in 'where clause'
in SYSTEMPATH\Database\MySQLi\Connection.php on line 292.
 1 SYSTEMPATH\Database\MySQLi\Connection.php(292): mysqli->query('SELECT `gender`.`id_gender` as `idgender`, `sex`, `nama_kamar`, `id_kamar`
FROM `gender`
JOIN `kamar_santri` ON `kamar_santri`.`gender_id` = `id_gender`
WHERE `idgender` = \'2\'', 0)
 2 SYSTEMPATH\Database\BaseConnection.php(693): CodeIgniter\Database\MySQLi\Connection->execute('SELECT `gender`.`id_gender` as `idgender`, `sex`, `nama_kamar`, `id_kamar`
FROM `gender`
JOIN `kamar_santri` ON `kamar_santri`.`gender_id` = `id_gender`
WHERE `idgender` = \'2\'')
 3 SYSTEMPATH\Database\BaseConnection.php(620): CodeIgniter\Database\BaseConnection->simpleQuery('SELECT `gender`.`id_gender` as `idgender`, `sex`, `nama_kamar`, `id_kamar`
FROM `gender`
JOIN `kamar_santri` ON `kamar_santri`.`gender_id` = `id_gender`
WHERE `idgender` = \'2\'')
 4 SYSTEMPATH\Database\BaseBuilder.php(1585): CodeIgniter\Database\BaseConnection->query('SELECT `gender`.`id_gender` as `idgender`, `sex`, `nama_kamar`, `id_kamar`
FROM `gender`
JOIN `kamar_santri` ON `kamar_santri`.`gender_id` = `id_gender`
WHERE `idgender` = :idgender:', [...], false)
 5 APPPATH\Controllers\Admin.php(72): CodeIgniter\Database\BaseBuilder->get()
 6 SYSTEMPATH\CodeIgniter.php(902): App\Controllers\Admin->save()
 7 SYSTEMPATH\CodeIgniter.php(457): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Admin))
 8 SYSTEMPATH\CodeIgniter.php(340): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 9 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
10 SYSTEMPATH\Commands\Server\rewrite.php(46): require_once('FCPATH\\index.php')
CRITICAL - 2022-12-03 03:00:36 --> date() expects at least 1 parameter, 0 given
in APPPATH\Controllers\Admin.php on line 86.
 1 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(2, 'date() expects at least 1 parameter, 0 given', 'APPPATH\\Controllers\\Admin.php', 86, [...])
 2 APPPATH\Controllers\Admin.php(86): date()
 3 SYSTEMPATH\CodeIgniter.php(902): App\Controllers\Admin->save()
 4 SYSTEMPATH\CodeIgniter.php(457): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Admin))
 5 SYSTEMPATH\CodeIgniter.php(340): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 6 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
 7 SYSTEMPATH\Commands\Server\rewrite.php(46): require_once('FCPATH\\index.php')
CRITICAL - 2022-12-03 03:01:09 --> Object of class CodeIgniter\Database\MySQLi\Result could not be converted to string
in SYSTEMPATH\Database\Query.php on line 335.
 1 SYSTEMPATH\Database\Query.php(335): strtr('INSERT INTO `users` (`username`, `fullname`, `no_telp`, `email`, `jk`, `kamar`, `thn_masuk`, `wali`, `no_wali`, `password_hash`, `created_at`) VALUES (:username:, :fullname:, :no_telp:, :email:, :jk:, :kamar:, :thn_masuk:, :wali:, :no_wali:, :password_hash:, :created_at:)', [...])
 2 SYSTEMPATH\Database\Query.php(310): CodeIgniter\Database\Query->matchNamedBinds('INSERT INTO `users` (`username`, `fullname`, `no_telp`, `email`, `jk`, `kamar`, `thn_masuk`, `wali`, `no_wali`, `password_hash`, `created_at`) VALUES (:username:, :fullname:, :no_telp:, :email:, :jk:, :kamar:, :thn_masuk:, :wali:, :no_wali:, :password_hash:, :created_at:)', [...])
 3 SYSTEMPATH\Database\Query.php(159): CodeIgniter\Database\Query->compileBinds()
 4 SYSTEMPATH\Database\BaseConnection.php(620): CodeIgniter\Database\Query->getQuery()
 5 SYSTEMPATH\Database\BaseBuilder.php(1916): CodeIgniter\Database\BaseConnection->query('INSERT INTO `users` (`username`, `fullname`, `no_telp`, `email`, `jk`, `kamar`, `thn_masuk`, `wali`, `no_wali`, `password_hash`, `created_at`) VALUES (:username:, :fullname:, :no_telp:, :email:, :jk:, :kamar:, :thn_masuk:, :wali:, :no_wali:, :password_hash:, :created_at:)', [...], false)
 6 APPPATH\Controllers\Admin.php(88): CodeIgniter\Database\BaseBuilder->insert([...])
 7 SYSTEMPATH\CodeIgniter.php(902): App\Controllers\Admin->save()
 8 SYSTEMPATH\CodeIgniter.php(457): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Admin))
 9 SYSTEMPATH\CodeIgniter.php(340): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
10 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
11 SYSTEMPATH\Commands\Server\rewrite.php(46): require_once('FCPATH\\index.php')
CRITICAL - 2022-12-03 03:06:02 --> Call to undefined method CodeIgniter\Database\MySQLi\Builder::getRow()
in APPPATH\Controllers\Admin.php on line 72.
 1 SYSTEMPATH\CodeIgniter.php(902): App\Controllers\Admin->save()
 2 SYSTEMPATH\CodeIgniter.php(457): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Admin))
 3 SYSTEMPATH\CodeIgniter.php(340): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 4 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
 5 SYSTEMPATH\Commands\Server\rewrite.php(46): require_once('FCPATH\\index.php')
ERROR - 2022-12-03 03:10:57 --> mysqli_sql_exception: Duplicate entry 'qwerty@qwq' for key 'email' in C:\xampp\htdocs\tugas_akhir\vendor\codeigniter4\framework\system\Database\MySQLi\Connection.php:292
Stack trace:
#0 C:\xampp\htdocs\tugas_akhir\vendor\codeigniter4\framework\system\Database\MySQLi\Connection.php(292): mysqli->query('INSERT INTO `us...', 0)
#1 C:\xampp\htdocs\tugas_akhir\vendor\codeigniter4\framework\system\Database\BaseConnection.php(693): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `us...')
#2 C:\xampp\htdocs\tugas_akhir\vendor\codeigniter4\framework\system\Database\BaseConnection.php(620): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `us...')
#3 C:\xampp\htdocs\tugas_akhir\vendor\codeigniter4\framework\system\Database\BaseBuilder.php(1916): CodeIgniter\Database\BaseConnection->query('INSERT INTO `us...', Array, false)
#4 C:\xampp\htdocs\tugas_akhir\app\Controllers\Admin.php(78): CodeIgniter\Database\BaseBuilder->insert(Array)
#5 C:\xampp\htdocs\tugas_akhir\vendor\codeigniter4\framework\system\CodeIgniter.php(902): App\Controllers\Admin->save()
#6 C:\xampp\htdocs\tugas_akhir\vendor\codeigniter4\framework\system\CodeIgniter.php(457): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Admin))
#7 C:\xampp\htdocs\tugas_akhir\vendor\codeigniter4\framework\system\CodeIgniter.php(340): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#8 C:\xampp\htdocs\tugas_akhir\public\index.php(67): CodeIgniter\CodeIgniter->run()
#9 C:\xampp\htdocs\tugas_akhir\vendor\codeigniter4\framework\system\Commands\Server\rewrite.php(46): require_once('C:\\xampp\\htdocs...')
#10 {main}
CRITICAL - 2022-12-03 03:10:57 --> Duplicate entry 'qwerty@qwq' for key 'email'
in SYSTEMPATH\Database\MySQLi\Connection.php on line 292.
 1 SYSTEMPATH\Database\MySQLi\Connection.php(292): mysqli->query('INSERT INTO `users` (`username`, `fullname`, `no_telp`, `email`, `jk`, `kamar`, `thn_masuk`, `wali`, `no_wali`, `password_hash`, `created_at`) VALUES (\'qwerty\', \'qwerty\', \'8388607\', \'qwerty@qwq\', \'2\', \'36\', \'2012\', \'qwerty\', \'8388607\', \'$2y$10$VmiCFM8elgi8abYLiWs6Veq.JEegD6E9.dwlvTCdh70fOXBaItIt6\', 1670058657)', 0)
 2 SYSTEMPATH\Database\BaseConnection.php(693): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `users` (`username`, `fullname`, `no_telp`, `email`, `jk`, `kamar`, `thn_masuk`, `wali`, `no_wali`, `password_hash`, `created_at`) VALUES (\'qwerty\', \'qwerty\', \'8388607\', \'qwerty@qwq\', \'2\', \'36\', \'2012\', \'qwerty\', \'8388607\', \'$2y$10$VmiCFM8elgi8abYLiWs6Veq.JEegD6E9.dwlvTCdh70fOXBaItIt6\', 1670058657)')
 3 SYSTEMPATH\Database\BaseConnection.php(620): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `users` (`username`, `fullname`, `no_telp`, `email`, `jk`, `kamar`, `thn_masuk`, `wali`, `no_wali`, `password_hash`, `created_at`) VALUES (\'qwerty\', \'qwerty\', \'8388607\', \'qwerty@qwq\', \'2\', \'36\', \'2012\', \'qwerty\', \'8388607\', \'$2y$10$VmiCFM8elgi8abYLiWs6Veq.JEegD6E9.dwlvTCdh70fOXBaItIt6\', 1670058657)')
 4 SYSTEMPATH\Database\BaseBuilder.php(1916): CodeIgniter\Database\BaseConnection->query('INSERT INTO `users` (`username`, `fullname`, `no_telp`, `email`, `jk`, `kamar`, `thn_masuk`, `wali`, `no_wali`, `password_hash`, `created_at`) VALUES (:username:, :fullname:, :no_telp:, :email:, :jk:, :kamar:, :thn_masuk:, :wali:, :no_wali:, :password_hash:, :created_at:)', [...], false)
 5 APPPATH\Controllers\Admin.php(78): CodeIgniter\Database\BaseBuilder->insert([...])
 6 SYSTEMPATH\CodeIgniter.php(902): App\Controllers\Admin->save()
 7 SYSTEMPATH\CodeIgniter.php(457): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Admin))
 8 SYSTEMPATH\CodeIgniter.php(340): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 9 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
10 SYSTEMPATH\Commands\Server\rewrite.php(46): require_once('FCPATH\\index.php')
ERROR - 2022-12-03 03:11:31 --> mysqli_sql_exception: Duplicate entry 'qwerty@qwq' for key 'email' in C:\xampp\htdocs\tugas_akhir\vendor\codeigniter4\framework\system\Database\MySQLi\Connection.php:292
Stack trace:
#0 C:\xampp\htdocs\tugas_akhir\vendor\codeigniter4\framework\system\Database\MySQLi\Connection.php(292): mysqli->query('INSERT INTO `us...', 0)
#1 C:\xampp\htdocs\tugas_akhir\vendor\codeigniter4\framework\system\Database\BaseConnection.php(693): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `us...')
#2 C:\xampp\htdocs\tugas_akhir\vendor\codeigniter4\framework\system\Database\BaseConnection.php(620): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `us...')
#3 C:\xampp\htdocs\tugas_akhir\vendor\codeigniter4\framework\system\Database\BaseBuilder.php(1916): CodeIgniter\Database\BaseConnection->query('INSERT INTO `us...', Array, false)
#4 C:\xampp\htdocs\tugas_akhir\app\Controllers\Admin.php(78): CodeIgniter\Database\BaseBuilder->insert(Array)
#5 C:\xampp\htdocs\tugas_akhir\vendor\codeigniter4\framework\system\CodeIgniter.php(902): App\Controllers\Admin->save()
#6 C:\xampp\htdocs\tugas_akhir\vendor\codeigniter4\framework\system\CodeIgniter.php(457): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Admin))
#7 C:\xampp\htdocs\tugas_akhir\vendor\codeigniter4\framework\system\CodeIgniter.php(340): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#8 C:\xampp\htdocs\tugas_akhir\public\index.php(67): CodeIgniter\CodeIgniter->run()
#9 C:\xampp\htdocs\tugas_akhir\vendor\codeigniter4\framework\system\Commands\Server\rewrite.php(46): require_once('C:\\xampp\\htdocs...')
#10 {main}
CRITICAL - 2022-12-03 03:11:31 --> Duplicate entry 'qwerty@qwq' for key 'email'
in SYSTEMPATH\Database\MySQLi\Connection.php on line 292.
 1 SYSTEMPATH\Database\MySQLi\Connection.php(292): mysqli->query('INSERT INTO `users` (`username`, `fullname`, `no_telp`, `email`, `jk`, `kamar`, `thn_masuk`, `wali`, `no_wali`, `password_hash`, `created_at`) VALUES (\'qwertyuiop\', \'qwerty\', \'8388607\', \'qwerty@qwq\', \'1\', \'13\', \'2012\', \'qwerty\', \'8388607\', \'$2y$10$VmiCFM8elgi8abYLiWs6Veq.JEegD6E9.dwlvTCdh70fOXBaItIt6\', 1670058691)', 0)
 2 SYSTEMPATH\Database\BaseConnection.php(693): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `users` (`username`, `fullname`, `no_telp`, `email`, `jk`, `kamar`, `thn_masuk`, `wali`, `no_wali`, `password_hash`, `created_at`) VALUES (\'qwertyuiop\', \'qwerty\', \'8388607\', \'qwerty@qwq\', \'1\', \'13\', \'2012\', \'qwerty\', \'8388607\', \'$2y$10$VmiCFM8elgi8abYLiWs6Veq.JEegD6E9.dwlvTCdh70fOXBaItIt6\', 1670058691)')
 3 SYSTEMPATH\Database\BaseConnection.php(620): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `users` (`username`, `fullname`, `no_telp`, `email`, `jk`, `kamar`, `thn_masuk`, `wali`, `no_wali`, `password_hash`, `created_at`) VALUES (\'qwertyuiop\', \'qwerty\', \'8388607\', \'qwerty@qwq\', \'1\', \'13\', \'2012\', \'qwerty\', \'8388607\', \'$2y$10$VmiCFM8elgi8abYLiWs6Veq.JEegD6E9.dwlvTCdh70fOXBaItIt6\', 1670058691)')
 4 SYSTEMPATH\Database\BaseBuilder.php(1916): CodeIgniter\Database\BaseConnection->query('INSERT INTO `users` (`username`, `fullname`, `no_telp`, `email`, `jk`, `kamar`, `thn_masuk`, `wali`, `no_wali`, `password_hash`, `created_at`) VALUES (:username:, :fullname:, :no_telp:, :email:, :jk:, :kamar:, :thn_masuk:, :wali:, :no_wali:, :password_hash:, :created_at:)', [...], false)
 5 APPPATH\Controllers\Admin.php(78): CodeIgniter\Database\BaseBuilder->insert([...])
 6 SYSTEMPATH\CodeIgniter.php(902): App\Controllers\Admin->save()
 7 SYSTEMPATH\CodeIgniter.php(457): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Admin))
 8 SYSTEMPATH\CodeIgniter.php(340): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 9 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
10 SYSTEMPATH\Commands\Server\rewrite.php(46): require_once('FCPATH\\index.php')
CRITICAL - 2022-12-03 11:27:11 --> date() expects parameter 2 to be int, string given
in APPPATH\Controllers\Admin.php on line 76.
 1 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(2, 'date() expects parameter 2 to be int, string given', 'APPPATH\\Controllers\\Admin.php', 76, [])
 2 APPPATH\Controllers\Admin.php(76): date('Y-m-d H-i-s', 'Asia/Jakarta')
 3 SYSTEMPATH\CodeIgniter.php(902): App\Controllers\Admin->save()
 4 SYSTEMPATH\CodeIgniter.php(457): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Admin))
 5 SYSTEMPATH\CodeIgniter.php(340): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 6 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
 7 SYSTEMPATH\Commands\Server\rewrite.php(46): require_once('FCPATH\\index.php')
ERROR - 2022-12-03 11:31:28 --> mysqli_sql_exception: Duplicate entry 'elscine@gmail.com' for key 'email' in C:\xampp\htdocs\tugas_akhir\vendor\codeigniter4\framework\system\Database\MySQLi\Connection.php:292
Stack trace:
#0 C:\xampp\htdocs\tugas_akhir\vendor\codeigniter4\framework\system\Database\MySQLi\Connection.php(292): mysqli->query('INSERT INTO `us...', 0)
#1 C:\xampp\htdocs\tugas_akhir\vendor\codeigniter4\framework\system\Database\BaseConnection.php(693): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `us...')
#2 C:\xampp\htdocs\tugas_akhir\vendor\codeigniter4\framework\system\Database\BaseConnection.php(620): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `us...')
#3 C:\xampp\htdocs\tugas_akhir\vendor\codeigniter4\framework\system\Database\BaseBuilder.php(1916): CodeIgniter\Database\BaseConnection->query('INSERT INTO `us...', Array, false)
#4 C:\xampp\htdocs\tugas_akhir\app\Controllers\Admin.php(78): CodeIgniter\Database\BaseBuilder->insert(Array)
#5 C:\xampp\htdocs\tugas_akhir\vendor\codeigniter4\framework\system\CodeIgniter.php(902): App\Controllers\Admin->save()
#6 C:\xampp\htdocs\tugas_akhir\vendor\codeigniter4\framework\system\CodeIgniter.php(457): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Admin))
#7 C:\xampp\htdocs\tugas_akhir\vendor\codeigniter4\framework\system\CodeIgniter.php(340): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#8 C:\xampp\htdocs\tugas_akhir\public\index.php(67): CodeIgniter\CodeIgniter->run()
#9 C:\xampp\htdocs\tugas_akhir\vendor\codeigniter4\framework\system\Commands\Server\rewrite.php(46): require_once('C:\\xampp\\htdocs...')
#10 {main}
CRITICAL - 2022-12-03 11:31:28 --> Duplicate entry 'elscine@gmail.com' for key 'email'
in SYSTEMPATH\Database\MySQLi\Connection.php on line 292.
 1 SYSTEMPATH\Database\MySQLi\Connection.php(292): mysqli->query('INSERT INTO `users` (`username`, `fullname`, `no_telp`, `email`, `jk`, `kamar`, `thn_masuk`, `wali`, `no_wali`, `password_hash`, `created_at`) VALUES (\'elscine\', \'Elscine\', \'082331203169\', \'elscine@gmail.com\', \'2\', \'50\', \'2015\', \'wali\', \'082331203169\', \'$2y$10$VmiCFM8elgi8abYLiWs6Veq.JEegD6E9.dwlvTCdh70fOXBaItIt6\', \'2022-12-03 18-31-28\')', 0)
 2 SYSTEMPATH\Database\BaseConnection.php(693): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `users` (`username`, `fullname`, `no_telp`, `email`, `jk`, `kamar`, `thn_masuk`, `wali`, `no_wali`, `password_hash`, `created_at`) VALUES (\'elscine\', \'Elscine\', \'082331203169\', \'elscine@gmail.com\', \'2\', \'50\', \'2015\', \'wali\', \'082331203169\', \'$2y$10$VmiCFM8elgi8abYLiWs6Veq.JEegD6E9.dwlvTCdh70fOXBaItIt6\', \'2022-12-03 18-31-28\')')
 3 SYSTEMPATH\Database\BaseConnection.php(620): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `users` (`username`, `fullname`, `no_telp`, `email`, `jk`, `kamar`, `thn_masuk`, `wali`, `no_wali`, `password_hash`, `created_at`) VALUES (\'elscine\', \'Elscine\', \'082331203169\', \'elscine@gmail.com\', \'2\', \'50\', \'2015\', \'wali\', \'082331203169\', \'$2y$10$VmiCFM8elgi8abYLiWs6Veq.JEegD6E9.dwlvTCdh70fOXBaItIt6\', \'2022-12-03 18-31-28\')')
 4 SYSTEMPATH\Database\BaseBuilder.php(1916): CodeIgniter\Database\BaseConnection->query('INSERT INTO `users` (`username`, `fullname`, `no_telp`, `email`, `jk`, `kamar`, `thn_masuk`, `wali`, `no_wali`, `password_hash`, `created_at`) VALUES (:username:, :fullname:, :no_telp:, :email:, :jk:, :kamar:, :thn_masuk:, :wali:, :no_wali:, :password_hash:, :created_at:)', [...], false)
 5 APPPATH\Controllers\Admin.php(78): CodeIgniter\Database\BaseBuilder->insert([...])
 6 SYSTEMPATH\CodeIgniter.php(902): App\Controllers\Admin->save()
 7 SYSTEMPATH\CodeIgniter.php(457): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Admin))
 8 SYSTEMPATH\CodeIgniter.php(340): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 9 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
10 SYSTEMPATH\Commands\Server\rewrite.php(46): require_once('FCPATH\\index.php')
ERROR - 2022-12-03 11:31:59 --> mysqli_sql_exception: Duplicate entry 'elscine' for key 'username' in C:\xampp\htdocs\tugas_akhir\vendor\codeigniter4\framework\system\Database\MySQLi\Connection.php:292
Stack trace:
#0 C:\xampp\htdocs\tugas_akhir\vendor\codeigniter4\framework\system\Database\MySQLi\Connection.php(292): mysqli->query('INSERT INTO `us...', 0)
#1 C:\xampp\htdocs\tugas_akhir\vendor\codeigniter4\framework\system\Database\BaseConnection.php(693): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `us...')
#2 C:\xampp\htdocs\tugas_akhir\vendor\codeigniter4\framework\system\Database\BaseConnection.php(620): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `us...')
#3 C:\xampp\htdocs\tugas_akhir\vendor\codeigniter4\framework\system\Database\BaseBuilder.php(1916): CodeIgniter\Database\BaseConnection->query('INSERT INTO `us...', Array, false)
#4 C:\xampp\htdocs\tugas_akhir\app\Controllers\Admin.php(78): CodeIgniter\Database\BaseBuilder->insert(Array)
#5 C:\xampp\htdocs\tugas_akhir\vendor\codeigniter4\framework\system\CodeIgniter.php(902): App\Controllers\Admin->save()
#6 C:\xampp\htdocs\tugas_akhir\vendor\codeigniter4\framework\system\CodeIgniter.php(457): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Admin))
#7 C:\xampp\htdocs\tugas_akhir\vendor\codeigniter4\framework\system\CodeIgniter.php(340): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#8 C:\xampp\htdocs\tugas_akhir\public\index.php(67): CodeIgniter\CodeIgniter->run()
#9 C:\xampp\htdocs\tugas_akhir\vendor\codeigniter4\framework\system\Commands\Server\rewrite.php(46): require_once('C:\\xampp\\htdocs...')
#10 {main}
CRITICAL - 2022-12-03 11:31:59 --> Duplicate entry 'elscine' for key 'username'
in SYSTEMPATH\Database\MySQLi\Connection.php on line 292.
 1 SYSTEMPATH\Database\MySQLi\Connection.php(292): mysqli->query('INSERT INTO `users` (`username`, `fullname`, `no_telp`, `email`, `jk`, `kamar`, `thn_masuk`, `wali`, `no_wali`, `password_hash`, `created_at`) VALUES (\'elscine\', \'Elscine\', \'082331203169\', \'elscine@elscine\', \'2\', \'38\', \'2015\', \'wali\', \'082331203169\', \'$2y$10$VmiCFM8elgi8abYLiWs6Veq.JEegD6E9.dwlvTCdh70fOXBaItIt6\', \'2022-12-03 18-31-59\')', 0)
 2 SYSTEMPATH\Database\BaseConnection.php(693): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `users` (`username`, `fullname`, `no_telp`, `email`, `jk`, `kamar`, `thn_masuk`, `wali`, `no_wali`, `password_hash`, `created_at`) VALUES (\'elscine\', \'Elscine\', \'082331203169\', \'elscine@elscine\', \'2\', \'38\', \'2015\', \'wali\', \'082331203169\', \'$2y$10$VmiCFM8elgi8abYLiWs6Veq.JEegD6E9.dwlvTCdh70fOXBaItIt6\', \'2022-12-03 18-31-59\')')
 3 SYSTEMPATH\Database\BaseConnection.php(620): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `users` (`username`, `fullname`, `no_telp`, `email`, `jk`, `kamar`, `thn_masuk`, `wali`, `no_wali`, `password_hash`, `created_at`) VALUES (\'elscine\', \'Elscine\', \'082331203169\', \'elscine@elscine\', \'2\', \'38\', \'2015\', \'wali\', \'082331203169\', \'$2y$10$VmiCFM8elgi8abYLiWs6Veq.JEegD6E9.dwlvTCdh70fOXBaItIt6\', \'2022-12-03 18-31-59\')')
 4 SYSTEMPATH\Database\BaseBuilder.php(1916): CodeIgniter\Database\BaseConnection->query('INSERT INTO `users` (`username`, `fullname`, `no_telp`, `email`, `jk`, `kamar`, `thn_masuk`, `wali`, `no_wali`, `password_hash`, `created_at`) VALUES (:username:, :fullname:, :no_telp:, :email:, :jk:, :kamar:, :thn_masuk:, :wali:, :no_wali:, :password_hash:, :created_at:)', [...], false)
 5 APPPATH\Controllers\Admin.php(78): CodeIgniter\Database\BaseBuilder->insert([...])
 6 SYSTEMPATH\CodeIgniter.php(902): App\Controllers\Admin->save()
 7 SYSTEMPATH\CodeIgniter.php(457): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Admin))
 8 SYSTEMPATH\CodeIgniter.php(340): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 9 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
10 SYSTEMPATH\Commands\Server\rewrite.php(46): require_once('FCPATH\\index.php')
CRITICAL - 2022-12-03 12:22:07 --> Array to string conversion
in APPPATH\Views\admin\data_santri.php on line 235.
 1 APPPATH\Views\admin\data_santri.php(235): CodeIgniter\Debug\Exceptions->errorHandler(8, 'Array to string conversion', 'APPPATH\\Views\\admin\\data_santri.php', 235, [...])
 2 SYSTEMPATH\View\View.php(213): include('APPPATH\\Views\\admin\\data_santri.php')
 3 SYSTEMPATH\View\View.php(216): CodeIgniter\View\View->CodeIgniter\View\{closure}()
 4 SYSTEMPATH\Common.php(1142): CodeIgniter\View\View->render('admin/data_santri', [], true)
 5 APPPATH\Controllers\Admin.php(39): view('admin/data_santri', [...])
 6 SYSTEMPATH\CodeIgniter.php(902): App\Controllers\Admin->data_santri()
 7 SYSTEMPATH\CodeIgniter.php(457): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Admin))
 8 SYSTEMPATH\CodeIgniter.php(340): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 9 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
10 SYSTEMPATH\Commands\Server\rewrite.php(46): require_once('FCPATH\\index.php')
ERROR - 2022-12-03 12:29:36 --> mysqli_sql_exception: Duplicate entry '123@gmail' for key 'email' in C:\xampp\htdocs\tugas_akhir\vendor\codeigniter4\framework\system\Database\MySQLi\Connection.php:292
Stack trace:
#0 C:\xampp\htdocs\tugas_akhir\vendor\codeigniter4\framework\system\Database\MySQLi\Connection.php(292): mysqli->query('INSERT INTO `us...', 0)
#1 C:\xampp\htdocs\tugas_akhir\vendor\codeigniter4\framework\system\Database\BaseConnection.php(693): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `us...')
#2 C:\xampp\htdocs\tugas_akhir\vendor\codeigniter4\framework\system\Database\BaseConnection.php(620): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `us...')
#3 C:\xampp\htdocs\tugas_akhir\vendor\codeigniter4\framework\system\Database\BaseBuilder.php(1916): CodeIgniter\Database\BaseConnection->query('INSERT INTO `us...', Array, false)
#4 C:\xampp\htdocs\tugas_akhir\app\Controllers\Admin.php(83): CodeIgniter\Database\BaseBuilder->insert(Array)
#5 C:\xampp\htdocs\tugas_akhir\vendor\codeigniter4\framework\system\CodeIgniter.php(902): App\Controllers\Admin->save()
#6 C:\xampp\htdocs\tugas_akhir\vendor\codeigniter4\framework\system\CodeIgniter.php(457): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Admin))
#7 C:\xampp\htdocs\tugas_akhir\vendor\codeigniter4\framework\system\CodeIgniter.php(340): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#8 C:\xampp\htdocs\tugas_akhir\public\index.php(67): CodeIgniter\CodeIgniter->run()
#9 C:\xampp\htdocs\tugas_akhir\vendor\codeigniter4\framework\system\Commands\Server\rewrite.php(46): require_once('C:\\xampp\\htdocs...')
#10 {main}
CRITICAL - 2022-12-03 12:29:36 --> Duplicate entry '123@gmail' for key 'email'
in SYSTEMPATH\Database\MySQLi\Connection.php on line 292.
 1 SYSTEMPATH\Database\MySQLi\Connection.php(292): mysqli->query('INSERT INTO `users` (`username`, `fullname`, `no_telp`, `email`, `jk`, `kamar`, `thn_masuk`, `wali`, `no_wali`, `password_hash`, `created_at`) VALUES (\'mi\', \'Ahmad Muhlish Tri Cahyo\', \'082331203169\', \'123@gmail\', \'1\', \'16\', \'2020\', \'qwerty\', \'082331203169\', \'$2y$10$VmiCFM8elgi8abYLiWs6Veq.JEegD6E9.dwlvTCdh70fOXBaItIt6\', \'2022-12-04 01-29-36\')', 0)
 2 SYSTEMPATH\Database\BaseConnection.php(693): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `users` (`username`, `fullname`, `no_telp`, `email`, `jk`, `kamar`, `thn_masuk`, `wali`, `no_wali`, `password_hash`, `created_at`) VALUES (\'mi\', \'Ahmad Muhlish Tri Cahyo\', \'082331203169\', \'123@gmail\', \'1\', \'16\', \'2020\', \'qwerty\', \'082331203169\', \'$2y$10$VmiCFM8elgi8abYLiWs6Veq.JEegD6E9.dwlvTCdh70fOXBaItIt6\', \'2022-12-04 01-29-36\')')
 3 SYSTEMPATH\Database\BaseConnection.php(620): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `users` (`username`, `fullname`, `no_telp`, `email`, `jk`, `kamar`, `thn_masuk`, `wali`, `no_wali`, `password_hash`, `created_at`) VALUES (\'mi\', \'Ahmad Muhlish Tri Cahyo\', \'082331203169\', \'123@gmail\', \'1\', \'16\', \'2020\', \'qwerty\', \'082331203169\', \'$2y$10$VmiCFM8elgi8abYLiWs6Veq.JEegD6E9.dwlvTCdh70fOXBaItIt6\', \'2022-12-04 01-29-36\')')
 4 SYSTEMPATH\Database\BaseBuilder.php(1916): CodeIgniter\Database\BaseConnection->query('INSERT INTO `users` (`username`, `fullname`, `no_telp`, `email`, `jk`, `kamar`, `thn_masuk`, `wali`, `no_wali`, `password_hash`, `created_at`) VALUES (:username:, :fullname:, :no_telp:, :email:, :jk:, :kamar:, :thn_masuk:, :wali:, :no_wali:, :password_hash:, :created_at:)', [...], false)
 5 APPPATH\Controllers\Admin.php(83): CodeIgniter\Database\BaseBuilder->insert([...])
 6 SYSTEMPATH\CodeIgniter.php(902): App\Controllers\Admin->save()
 7 SYSTEMPATH\CodeIgniter.php(457): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Admin))
 8 SYSTEMPATH\CodeIgniter.php(340): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 9 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
10 SYSTEMPATH\Commands\Server\rewrite.php(46): require_once('FCPATH\\index.php')
CRITICAL - 2022-12-03 12:29:49 --> Object of class App\Controllers\Admin could not be converted to string
in APPPATH\Controllers\Admin.php on line 86.
 1 SYSTEMPATH\CodeIgniter.php(902): App\Controllers\Admin->save()
 2 SYSTEMPATH\CodeIgniter.php(457): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Admin))
 3 SYSTEMPATH\CodeIgniter.php(340): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 4 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
 5 SYSTEMPATH\Commands\Server\rewrite.php(46): require_once('FCPATH\\index.php')
ERROR - 2022-12-03 12:31:25 --> mysqli_sql_exception: Duplicate entry '123@gmai' for key 'email' in C:\xampp\htdocs\tugas_akhir\vendor\codeigniter4\framework\system\Database\MySQLi\Connection.php:292
Stack trace:
#0 C:\xampp\htdocs\tugas_akhir\vendor\codeigniter4\framework\system\Database\MySQLi\Connection.php(292): mysqli->query('INSERT INTO `us...', 0)
#1 C:\xampp\htdocs\tugas_akhir\vendor\codeigniter4\framework\system\Database\BaseConnection.php(693): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `us...')
#2 C:\xampp\htdocs\tugas_akhir\vendor\codeigniter4\framework\system\Database\BaseConnection.php(620): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `us...')
#3 C:\xampp\htdocs\tugas_akhir\vendor\codeigniter4\framework\system\Database\BaseBuilder.php(1916): CodeIgniter\Database\BaseConnection->query('INSERT INTO `us...', Array, false)
#4 C:\xampp\htdocs\tugas_akhir\app\Controllers\Admin.php(83): CodeIgniter\Database\BaseBuilder->insert(Array)
#5 C:\xampp\htdocs\tugas_akhir\vendor\codeigniter4\framework\system\CodeIgniter.php(902): App\Controllers\Admin->save()
#6 C:\xampp\htdocs\tugas_akhir\vendor\codeigniter4\framework\system\CodeIgniter.php(457): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Admin))
#7 C:\xampp\htdocs\tugas_akhir\vendor\codeigniter4\framework\system\CodeIgniter.php(340): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#8 C:\xampp\htdocs\tugas_akhir\public\index.php(67): CodeIgniter\CodeIgniter->run()
#9 C:\xampp\htdocs\tugas_akhir\vendor\codeigniter4\framework\system\Commands\Server\rewrite.php(46): require_once('C:\\xampp\\htdocs...')
#10 {main}
CRITICAL - 2022-12-03 12:31:25 --> Duplicate entry '123@gmai' for key 'email'
in SYSTEMPATH\Database\MySQLi\Connection.php on line 292.
 1 SYSTEMPATH\Database\MySQLi\Connection.php(292): mysqli->query('INSERT INTO `users` (`username`, `fullname`, `no_telp`, `email`, `jk`, `kamar`, `thn_masuk`, `wali`, `no_wali`, `password_hash`, `created_at`) VALUES (\'mi\', \'Ahmad Muhlish Tri Cahyo\', \'082331203169\', \'123@gmai\', \'2\', \'36\', \'2020\', \'qwerty\', \'082331203169\', \'$2y$10$VmiCFM8elgi8abYLiWs6Veq.JEegD6E9.dwlvTCdh70fOXBaItIt6\', \'2022-12-04 01-31-25\')', 0)
 2 SYSTEMPATH\Database\BaseConnection.php(693): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `users` (`username`, `fullname`, `no_telp`, `email`, `jk`, `kamar`, `thn_masuk`, `wali`, `no_wali`, `password_hash`, `created_at`) VALUES (\'mi\', \'Ahmad Muhlish Tri Cahyo\', \'082331203169\', \'123@gmai\', \'2\', \'36\', \'2020\', \'qwerty\', \'082331203169\', \'$2y$10$VmiCFM8elgi8abYLiWs6Veq.JEegD6E9.dwlvTCdh70fOXBaItIt6\', \'2022-12-04 01-31-25\')')
 3 SYSTEMPATH\Database\BaseConnection.php(620): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `users` (`username`, `fullname`, `no_telp`, `email`, `jk`, `kamar`, `thn_masuk`, `wali`, `no_wali`, `password_hash`, `created_at`) VALUES (\'mi\', \'Ahmad Muhlish Tri Cahyo\', \'082331203169\', \'123@gmai\', \'2\', \'36\', \'2020\', \'qwerty\', \'082331203169\', \'$2y$10$VmiCFM8elgi8abYLiWs6Veq.JEegD6E9.dwlvTCdh70fOXBaItIt6\', \'2022-12-04 01-31-25\')')
 4 SYSTEMPATH\Database\BaseBuilder.php(1916): CodeIgniter\Database\BaseConnection->query('INSERT INTO `users` (`username`, `fullname`, `no_telp`, `email`, `jk`, `kamar`, `thn_masuk`, `wali`, `no_wali`, `password_hash`, `created_at`) VALUES (:username:, :fullname:, :no_telp:, :email:, :jk:, :kamar:, :thn_masuk:, :wali:, :no_wali:, :password_hash:, :created_at:)', [...], false)
 5 APPPATH\Controllers\Admin.php(83): CodeIgniter\Database\BaseBuilder->insert([...])
 6 SYSTEMPATH\CodeIgniter.php(902): App\Controllers\Admin->save()
 7 SYSTEMPATH\CodeIgniter.php(457): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Admin))
 8 SYSTEMPATH\CodeIgniter.php(340): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 9 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
10 SYSTEMPATH\Commands\Server\rewrite.php(46): require_once('FCPATH\\index.php')
ERROR - 2022-12-03 12:31:53 --> mysqli_sql_exception: Unknown column 'user_id' in 'field list' in C:\xampp\htdocs\tugas_akhir\vendor\codeigniter4\framework\system\Database\MySQLi\Connection.php:292
Stack trace:
#0 C:\xampp\htdocs\tugas_akhir\vendor\codeigniter4\framework\system\Database\MySQLi\Connection.php(292): mysqli->query('INSERT INTO `us...', 0)
#1 C:\xampp\htdocs\tugas_akhir\vendor\codeigniter4\framework\system\Database\BaseConnection.php(693): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `us...')
#2 C:\xampp\htdocs\tugas_akhir\vendor\codeigniter4\framework\system\Database\BaseConnection.php(620): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `us...')
#3 C:\xampp\htdocs\tugas_akhir\vendor\codeigniter4\framework\system\Database\BaseBuilder.php(1916): CodeIgniter\Database\BaseConnection->query('INSERT INTO `us...', Array, false)
#4 C:\xampp\htdocs\tugas_akhir\app\Controllers\Admin.php(86): CodeIgniter\Database\BaseBuilder->insert(Array)
#5 C:\xampp\htdocs\tugas_akhir\vendor\codeigniter4\framework\system\CodeIgniter.php(902): App\Controllers\Admin->save()
#6 C:\xampp\htdocs\tugas_akhir\vendor\codeigniter4\framework\system\CodeIgniter.php(457): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Admin))
#7 C:\xampp\htdocs\tugas_akhir\vendor\codeigniter4\framework\system\CodeIgniter.php(340): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#8 C:\xampp\htdocs\tugas_akhir\public\index.php(67): CodeIgniter\CodeIgniter->run()
#9 C:\xampp\htdocs\tugas_akhir\vendor\codeigniter4\framework\system\Commands\Server\rewrite.php(46): require_once('C:\\xampp\\htdocs...')
#10 {main}
CRITICAL - 2022-12-03 12:31:53 --> Unknown column 'user_id' in 'field list'
in SYSTEMPATH\Database\MySQLi\Connection.php on line 292.
 1 SYSTEMPATH\Database\MySQLi\Connection.php(292): mysqli->query('INSERT INTO `users` (`user_id`, `group_id`) VALUES (\'users.id\', 2)', 0)
 2 SYSTEMPATH\Database\BaseConnection.php(693): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `users` (`user_id`, `group_id`) VALUES (\'users.id\', 2)')
 3 SYSTEMPATH\Database\BaseConnection.php(620): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `users` (`user_id`, `group_id`) VALUES (\'users.id\', 2)')
 4 SYSTEMPATH\Database\BaseBuilder.php(1916): CodeIgniter\Database\BaseConnection->query('INSERT INTO `users` (`user_id`, `group_id`) VALUES (:user_id:, :group_id:)', [...], false)
 5 APPPATH\Controllers\Admin.php(86): CodeIgniter\Database\BaseBuilder->insert([...])
 6 SYSTEMPATH\CodeIgniter.php(902): App\Controllers\Admin->save()
 7 SYSTEMPATH\CodeIgniter.php(457): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Admin))
 8 SYSTEMPATH\CodeIgniter.php(340): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 9 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
10 SYSTEMPATH\Commands\Server\rewrite.php(46): require_once('FCPATH\\index.php')
ERROR - 2022-12-03 12:34:57 --> mysqli_sql_exception: Duplicate entry '123@gmai' for key 'email' in C:\xampp\htdocs\tugas_akhir\vendor\codeigniter4\framework\system\Database\MySQLi\Connection.php:292
Stack trace:
#0 C:\xampp\htdocs\tugas_akhir\vendor\codeigniter4\framework\system\Database\MySQLi\Connection.php(292): mysqli->query('INSERT INTO `us...', 0)
#1 C:\xampp\htdocs\tugas_akhir\vendor\codeigniter4\framework\system\Database\BaseConnection.php(693): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `us...')
#2 C:\xampp\htdocs\tugas_akhir\vendor\codeigniter4\framework\system\Database\BaseConnection.php(620): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `us...')
#3 C:\xampp\htdocs\tugas_akhir\vendor\codeigniter4\framework\system\Database\BaseBuilder.php(1916): CodeIgniter\Database\BaseConnection->query('INSERT INTO `us...', Array, false)
#4 C:\xampp\htdocs\tugas_akhir\app\Controllers\Admin.php(83): CodeIgniter\Database\BaseBuilder->insert(Array)
#5 C:\xampp\htdocs\tugas_akhir\vendor\codeigniter4\framework\system\CodeIgniter.php(902): App\Controllers\Admin->save()
#6 C:\xampp\htdocs\tugas_akhir\vendor\codeigniter4\framework\system\CodeIgniter.php(457): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Admin))
#7 C:\xampp\htdocs\tugas_akhir\vendor\codeigniter4\framework\system\CodeIgniter.php(340): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#8 C:\xampp\htdocs\tugas_akhir\public\index.php(67): CodeIgniter\CodeIgniter->run()
#9 C:\xampp\htdocs\tugas_akhir\vendor\codeigniter4\framework\system\Commands\Server\rewrite.php(46): require_once('C:\\xampp\\htdocs...')
#10 {main}
CRITICAL - 2022-12-03 12:34:57 --> Duplicate entry '123@gmai' for key 'email'
in SYSTEMPATH\Database\MySQLi\Connection.php on line 292.
 1 SYSTEMPATH\Database\MySQLi\Connection.php(292): mysqli->query('INSERT INTO `users` (`username`, `fullname`, `no_telp`, `email`, `jk`, `kamar`, `thn_masuk`, `wali`, `no_wali`, `password_hash`, `created_at`) VALUES (\'mi\', \'Ahmad Muhlish Tri Cahyo\', \'082331203169\', \'123@gmai\', \'2\', \'36\', \'2020\', \'qwerty\', \'082331203169\', \'$2y$10$VmiCFM8elgi8abYLiWs6Veq.JEegD6E9.dwlvTCdh70fOXBaItIt6\', \'2022-12-04 01-34-57\')', 0)
 2 SYSTEMPATH\Database\BaseConnection.php(693): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `users` (`username`, `fullname`, `no_telp`, `email`, `jk`, `kamar`, `thn_masuk`, `wali`, `no_wali`, `password_hash`, `created_at`) VALUES (\'mi\', \'Ahmad Muhlish Tri Cahyo\', \'082331203169\', \'123@gmai\', \'2\', \'36\', \'2020\', \'qwerty\', \'082331203169\', \'$2y$10$VmiCFM8elgi8abYLiWs6Veq.JEegD6E9.dwlvTCdh70fOXBaItIt6\', \'2022-12-04 01-34-57\')')
 3 SYSTEMPATH\Database\BaseConnection.php(620): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `users` (`username`, `fullname`, `no_telp`, `email`, `jk`, `kamar`, `thn_masuk`, `wali`, `no_wali`, `password_hash`, `created_at`) VALUES (\'mi\', \'Ahmad Muhlish Tri Cahyo\', \'082331203169\', \'123@gmai\', \'2\', \'36\', \'2020\', \'qwerty\', \'082331203169\', \'$2y$10$VmiCFM8elgi8abYLiWs6Veq.JEegD6E9.dwlvTCdh70fOXBaItIt6\', \'2022-12-04 01-34-57\')')
 4 SYSTEMPATH\Database\BaseBuilder.php(1916): CodeIgniter\Database\BaseConnection->query('INSERT INTO `users` (`username`, `fullname`, `no_telp`, `email`, `jk`, `kamar`, `thn_masuk`, `wali`, `no_wali`, `password_hash`, `created_at`) VALUES (:username:, :fullname:, :no_telp:, :email:, :jk:, :kamar:, :thn_masuk:, :wali:, :no_wali:, :password_hash:, :created_at:)', [...], false)
 5 APPPATH\Controllers\Admin.php(83): CodeIgniter\Database\BaseBuilder->insert([...])
 6 SYSTEMPATH\CodeIgniter.php(902): App\Controllers\Admin->save()
 7 SYSTEMPATH\CodeIgniter.php(457): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Admin))
 8 SYSTEMPATH\CodeIgniter.php(340): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 9 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
10 SYSTEMPATH\Commands\Server\rewrite.php(46): require_once('FCPATH\\index.php')
ERROR - 2022-12-03 12:35:24 --> mysqli_sql_exception: Unknown column 'user_id' in 'field list' in C:\xampp\htdocs\tugas_akhir\vendor\codeigniter4\framework\system\Database\MySQLi\Connection.php:292
Stack trace:
#0 C:\xampp\htdocs\tugas_akhir\vendor\codeigniter4\framework\system\Database\MySQLi\Connection.php(292): mysqli->query('INSERT INTO `us...', 0)
#1 C:\xampp\htdocs\tugas_akhir\vendor\codeigniter4\framework\system\Database\BaseConnection.php(693): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `us...')
#2 C:\xampp\htdocs\tugas_akhir\vendor\codeigniter4\framework\system\Database\BaseConnection.php(620): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `us...')
#3 C:\xampp\htdocs\tugas_akhir\vendor\codeigniter4\framework\system\Database\BaseBuilder.php(1916): CodeIgniter\Database\BaseConnection->query('INSERT INTO `us...', Array, false)
#4 C:\xampp\htdocs\tugas_akhir\app\Controllers\Admin.php(87): CodeIgniter\Database\BaseBuilder->insert(Array)
#5 C:\xampp\htdocs\tugas_akhir\vendor\codeigniter4\framework\system\CodeIgniter.php(902): App\Controllers\Admin->save()
#6 C:\xampp\htdocs\tugas_akhir\vendor\codeigniter4\framework\system\CodeIgniter.php(457): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Admin))
#7 C:\xampp\htdocs\tugas_akhir\vendor\codeigniter4\framework\system\CodeIgniter.php(340): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#8 C:\xampp\htdocs\tugas_akhir\public\index.php(67): CodeIgniter\CodeIgniter->run()
#9 C:\xampp\htdocs\tugas_akhir\vendor\codeigniter4\framework\system\Commands\Server\rewrite.php(46): require_once('C:\\xampp\\htdocs...')
#10 {main}
CRITICAL - 2022-12-03 12:35:24 --> Unknown column 'user_id' in 'field list'
in SYSTEMPATH\Database\MySQLi\Connection.php on line 292.
 1 SYSTEMPATH\Database\MySQLi\Connection.php(292): mysqli->query('INSERT INTO `users` (`user_id`, `group_id`) VALUES (\'usersid\', 2)', 0)
 2 SYSTEMPATH\Database\BaseConnection.php(693): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `users` (`user_id`, `group_id`) VALUES (\'usersid\', 2)')
 3 SYSTEMPATH\Database\BaseConnection.php(620): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `users` (`user_id`, `group_id`) VALUES (\'usersid\', 2)')
 4 SYSTEMPATH\Database\BaseBuilder.php(1916): CodeIgniter\Database\BaseConnection->query('INSERT INTO `users` (`user_id`, `group_id`) VALUES (:user_id:, :group_id:)', [...], false)
 5 APPPATH\Controllers\Admin.php(87): CodeIgniter\Database\BaseBuilder->insert([...])
 6 SYSTEMPATH\CodeIgniter.php(902): App\Controllers\Admin->save()
 7 SYSTEMPATH\CodeIgniter.php(457): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Admin))
 8 SYSTEMPATH\CodeIgniter.php(340): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 9 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
10 SYSTEMPATH\Commands\Server\rewrite.php(46): require_once('FCPATH\\index.php')
ERROR - 2022-12-03 12:38:58 --> mysqli_sql_exception: Cannot add or update a child row: a foreign key constraint fails (`tugas_akhir`.`auth_groups_users`, CONSTRAINT `auth_groups_users_user_id_foreign` FOREIGN KEY (`user_id`) REFERENCES `users` (`id`) ON DELETE CASCADE) in C:\xampp\htdocs\tugas_akhir\vendor\codeigniter4\framework\system\Database\MySQLi\Connection.php:292
Stack trace:
#0 C:\xampp\htdocs\tugas_akhir\vendor\codeigniter4\framework\system\Database\MySQLi\Connection.php(292): mysqli->query('INSERT INTO `au...', 0)
#1 C:\xampp\htdocs\tugas_akhir\vendor\codeigniter4\framework\system\Database\BaseConnection.php(693): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `au...')
#2 C:\xampp\htdocs\tugas_akhir\vendor\codeigniter4\framework\system\Database\BaseConnection.php(620): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `au...')
#3 C:\xampp\htdocs\tugas_akhir\vendor\codeigniter4\framework\system\Database\BaseBuilder.php(1916): CodeIgniter\Database\BaseConnection->query('INSERT INTO `au...', Array, false)
#4 C:\xampp\htdocs\tugas_akhir\app\Controllers\Admin.php(87): CodeIgniter\Database\BaseBuilder->insert(Array)
#5 C:\xampp\htdocs\tugas_akhir\vendor\codeigniter4\framework\system\CodeIgniter.php(902): App\Controllers\Admin->save()
#6 C:\xampp\htdocs\tugas_akhir\vendor\codeigniter4\framework\system\CodeIgniter.php(457): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Admin))
#7 C:\xampp\htdocs\tugas_akhir\vendor\codeigniter4\framework\system\CodeIgniter.php(340): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#8 C:\xampp\htdocs\tugas_akhir\public\index.php(67): CodeIgniter\CodeIgniter->run()
#9 C:\xampp\htdocs\tugas_akhir\vendor\codeigniter4\framework\system\Commands\Server\rewrite.php(46): require_once('C:\\xampp\\htdocs...')
#10 {main}
CRITICAL - 2022-12-03 12:38:58 --> Cannot add or update a child row: a foreign key constraint fails (`tugas_akhir`.`auth_groups_users`, CONSTRAINT `auth_groups_users_user_id_foreign` FOREIGN KEY (`user_id`) REFERENCES `users` (`id`) ON DELETE CASCADE)
in SYSTEMPATH\Database\MySQLi\Connection.php on line 292.
 1 SYSTEMPATH\Database\MySQLi\Connection.php(292): mysqli->query('INSERT INTO `auth_groups_users` (`user_id`, `group_id`) VALUES (\'users.id\', 2)', 0)
 2 SYSTEMPATH\Database\BaseConnection.php(693): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `auth_groups_users` (`user_id`, `group_id`) VALUES (\'users.id\', 2)')
 3 SYSTEMPATH\Database\BaseConnection.php(620): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `auth_groups_users` (`user_id`, `group_id`) VALUES (\'users.id\', 2)')
 4 SYSTEMPATH\Database\BaseBuilder.php(1916): CodeIgniter\Database\BaseConnection->query('INSERT INTO `auth_groups_users` (`user_id`, `group_id`) VALUES (:user_id:, :group_id:)', [...], false)
 5 APPPATH\Controllers\Admin.php(87): CodeIgniter\Database\BaseBuilder->insert([...])
 6 SYSTEMPATH\CodeIgniter.php(902): App\Controllers\Admin->save()
 7 SYSTEMPATH\CodeIgniter.php(457): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Admin))
 8 SYSTEMPATH\CodeIgniter.php(340): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 9 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
10 SYSTEMPATH\Commands\Server\rewrite.php(46): require_once('FCPATH\\index.php')
ERROR - 2022-12-03 12:39:54 --> mysqli_sql_exception: Unknown column 'user_id' in 'field list' in C:\xampp\htdocs\tugas_akhir\vendor\codeigniter4\framework\system\Database\MySQLi\Connection.php:292
Stack trace:
#0 C:\xampp\htdocs\tugas_akhir\vendor\codeigniter4\framework\system\Database\MySQLi\Connection.php(292): mysqli->query('INSERT INTO `us...', 0)
#1 C:\xampp\htdocs\tugas_akhir\vendor\codeigniter4\framework\system\Database\BaseConnection.php(693): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `us...')
#2 C:\xampp\htdocs\tugas_akhir\vendor\codeigniter4\framework\system\Database\BaseConnection.php(620): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `us...')
#3 C:\xampp\htdocs\tugas_akhir\vendor\codeigniter4\framework\system\Database\BaseBuilder.php(1916): CodeIgniter\Database\BaseConnection->query('INSERT INTO `us...', Array, false)
#4 C:\xampp\htdocs\tugas_akhir\app\Controllers\Admin.php(87): CodeIgniter\Database\BaseBuilder->insert(Array)
#5 C:\xampp\htdocs\tugas_akhir\vendor\codeigniter4\framework\system\CodeIgniter.php(902): App\Controllers\Admin->save()
#6 C:\xampp\htdocs\tugas_akhir\vendor\codeigniter4\framework\system\CodeIgniter.php(457): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Admin))
#7 C:\xampp\htdocs\tugas_akhir\vendor\codeigniter4\framework\system\CodeIgniter.php(340): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#8 C:\xampp\htdocs\tugas_akhir\public\index.php(67): CodeIgniter\CodeIgniter->run()
#9 C:\xampp\htdocs\tugas_akhir\vendor\codeigniter4\framework\system\Commands\Server\rewrite.php(46): require_once('C:\\xampp\\htdocs...')
#10 {main}
CRITICAL - 2022-12-03 12:39:54 --> Unknown column 'user_id' in 'field list'
in SYSTEMPATH\Database\MySQLi\Connection.php on line 292.
 1 SYSTEMPATH\Database\MySQLi\Connection.php(292): mysqli->query('INSERT INTO `users` (`user_id`, `group_id`) VALUES (\'users.id\', 2)', 0)
 2 SYSTEMPATH\Database\BaseConnection.php(693): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `users` (`user_id`, `group_id`) VALUES (\'users.id\', 2)')
 3 SYSTEMPATH\Database\BaseConnection.php(620): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `users` (`user_id`, `group_id`) VALUES (\'users.id\', 2)')
 4 SYSTEMPATH\Database\BaseBuilder.php(1916): CodeIgniter\Database\BaseConnection->query('INSERT INTO `users` (`user_id`, `group_id`) VALUES (:user_id:, :group_id:)', [...], false)
 5 APPPATH\Controllers\Admin.php(87): CodeIgniter\Database\BaseBuilder->insert([...])
 6 SYSTEMPATH\CodeIgniter.php(902): App\Controllers\Admin->save()
 7 SYSTEMPATH\CodeIgniter.php(457): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Admin))
 8 SYSTEMPATH\CodeIgniter.php(340): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 9 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
10 SYSTEMPATH\Commands\Server\rewrite.php(46): require_once('FCPATH\\index.php')
ERROR - 2022-12-03 12:41:04 --> mysqli_sql_exception: Unknown column 'group_id' in 'field list' in C:\xampp\htdocs\tugas_akhir\vendor\codeigniter4\framework\system\Database\MySQLi\Connection.php:292
Stack trace:
#0 C:\xampp\htdocs\tugas_akhir\vendor\codeigniter4\framework\system\Database\MySQLi\Connection.php(292): mysqli->query('INSERT INTO `us...', 0)
#1 C:\xampp\htdocs\tugas_akhir\vendor\codeigniter4\framework\system\Database\BaseConnection.php(693): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `us...')
#2 C:\xampp\htdocs\tugas_akhir\vendor\codeigniter4\framework\system\Database\BaseConnection.php(620): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `us...')
#3 C:\xampp\htdocs\tugas_akhir\vendor\codeigniter4\framework\system\Database\BaseBuilder.php(1916): CodeIgniter\Database\BaseConnection->query('INSERT INTO `us...', Array, false)
#4 C:\xampp\htdocs\tugas_akhir\app\Controllers\Admin.php(87): CodeIgniter\Database\BaseBuilder->insert(Array)
#5 C:\xampp\htdocs\tugas_akhir\vendor\codeigniter4\framework\system\CodeIgniter.php(902): App\Controllers\Admin->save()
#6 C:\xampp\htdocs\tugas_akhir\vendor\codeigniter4\framework\system\CodeIgniter.php(457): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Admin))
#7 C:\xampp\htdocs\tugas_akhir\vendor\codeigniter4\framework\system\CodeIgniter.php(340): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#8 C:\xampp\htdocs\tugas_akhir\public\index.php(67): CodeIgniter\CodeIgniter->run()
#9 C:\xampp\htdocs\tugas_akhir\vendor\codeigniter4\framework\system\Commands\Server\rewrite.php(46): require_once('C:\\xampp\\htdocs...')
#10 {main}
CRITICAL - 2022-12-03 12:41:04 --> Unknown column 'group_id' in 'field list'
in SYSTEMPATH\Database\MySQLi\Connection.php on line 292.
 1 SYSTEMPATH\Database\MySQLi\Connection.php(292): mysqli->query('INSERT INTO `users` (`group_id`, `user_id`) VALUES (2, \'users.id\')', 0)
 2 SYSTEMPATH\Database\BaseConnection.php(693): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `users` (`group_id`, `user_id`) VALUES (2, \'users.id\')')
 3 SYSTEMPATH\Database\BaseConnection.php(620): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `users` (`group_id`, `user_id`) VALUES (2, \'users.id\')')
 4 SYSTEMPATH\Database\BaseBuilder.php(1916): CodeIgniter\Database\BaseConnection->query('INSERT INTO `users` (`group_id`, `user_id`) VALUES (:group_id:, :user_id:)', [...], false)
 5 APPPATH\Controllers\Admin.php(87): CodeIgniter\Database\BaseBuilder->insert([...])
 6 SYSTEMPATH\CodeIgniter.php(902): App\Controllers\Admin->save()
 7 SYSTEMPATH\CodeIgniter.php(457): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Admin))
 8 SYSTEMPATH\CodeIgniter.php(340): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 9 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
10 SYSTEMPATH\Commands\Server\rewrite.php(46): require_once('FCPATH\\index.php')
ERROR - 2022-12-03 12:42:04 --> mysqli_sql_exception: Cannot add or update a child row: a foreign key constraint fails (`tugas_akhir`.`auth_groups_users`, CONSTRAINT `auth_groups_users_user_id_foreign` FOREIGN KEY (`user_id`) REFERENCES `users` (`id`) ON DELETE CASCADE) in C:\xampp\htdocs\tugas_akhir\vendor\codeigniter4\framework\system\Database\MySQLi\Connection.php:292
Stack trace:
#0 C:\xampp\htdocs\tugas_akhir\vendor\codeigniter4\framework\system\Database\MySQLi\Connection.php(292): mysqli->query('INSERT INTO `au...', 0)
#1 C:\xampp\htdocs\tugas_akhir\vendor\codeigniter4\framework\system\Database\BaseConnection.php(693): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `au...')
#2 C:\xampp\htdocs\tugas_akhir\vendor\codeigniter4\framework\system\Database\BaseConnection.php(620): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `au...')
#3 C:\xampp\htdocs\tugas_akhir\vendor\codeigniter4\framework\system\Database\BaseBuilder.php(1916): CodeIgniter\Database\BaseConnection->query('INSERT INTO `au...', Array, false)
#4 C:\xampp\htdocs\tugas_akhir\app\Controllers\Admin.php(87): CodeIgniter\Database\BaseBuilder->insert(Array)
#5 C:\xampp\htdocs\tugas_akhir\vendor\codeigniter4\framework\system\CodeIgniter.php(902): App\Controllers\Admin->save()
#6 C:\xampp\htdocs\tugas_akhir\vendor\codeigniter4\framework\system\CodeIgniter.php(457): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Admin))
#7 C:\xampp\htdocs\tugas_akhir\vendor\codeigniter4\framework\system\CodeIgniter.php(340): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#8 C:\xampp\htdocs\tugas_akhir\public\index.php(67): CodeIgniter\CodeIgniter->run()
#9 C:\xampp\htdocs\tugas_akhir\vendor\codeigniter4\framework\system\Commands\Server\rewrite.php(46): require_once('C:\\xampp\\htdocs...')
#10 {main}
CRITICAL - 2022-12-03 12:42:04 --> Cannot add or update a child row: a foreign key constraint fails (`tugas_akhir`.`auth_groups_users`, CONSTRAINT `auth_groups_users_user_id_foreign` FOREIGN KEY (`user_id`) REFERENCES `users` (`id`) ON DELETE CASCADE)
in SYSTEMPATH\Database\MySQLi\Connection.php on line 292.
 1 SYSTEMPATH\Database\MySQLi\Connection.php(292): mysqli->query('INSERT INTO `auth_groups_users` (`group_id`, `user_id`) VALUES (2, \'users.id\')', 0)
 2 SYSTEMPATH\Database\BaseConnection.php(693): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `auth_groups_users` (`group_id`, `user_id`) VALUES (2, \'users.id\')')
 3 SYSTEMPATH\Database\BaseConnection.php(620): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `auth_groups_users` (`group_id`, `user_id`) VALUES (2, \'users.id\')')
 4 SYSTEMPATH\Database\BaseBuilder.php(1916): CodeIgniter\Database\BaseConnection->query('INSERT INTO `auth_groups_users` (`group_id`, `user_id`) VALUES (:group_id:, :user_id:)', [...], false)
 5 APPPATH\Controllers\Admin.php(87): CodeIgniter\Database\BaseBuilder->insert([...])
 6 SYSTEMPATH\CodeIgniter.php(902): App\Controllers\Admin->save()
 7 SYSTEMPATH\CodeIgniter.php(457): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Admin))
 8 SYSTEMPATH\CodeIgniter.php(340): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 9 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
10 SYSTEMPATH\Commands\Server\rewrite.php(46): require_once('FCPATH\\index.php')
ERROR - 2022-12-03 12:48:04 --> mysqli_sql_exception: Cannot add or update a child row: a foreign key constraint fails (`tugas_akhir`.`auth_groups_users`, CONSTRAINT `auth_groups_users_user_id_foreign` FOREIGN KEY (`user_id`) REFERENCES `users` (`id`) ON DELETE CASCADE ON UPDATE CASCADE) in C:\xampp\htdocs\tugas_akhir\vendor\codeigniter4\framework\system\Database\MySQLi\Connection.php:292
Stack trace:
#0 C:\xampp\htdocs\tugas_akhir\vendor\codeigniter4\framework\system\Database\MySQLi\Connection.php(292): mysqli->query('INSERT INTO `au...', 0)
#1 C:\xampp\htdocs\tugas_akhir\vendor\codeigniter4\framework\system\Database\BaseConnection.php(693): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `au...')
#2 C:\xampp\htdocs\tugas_akhir\vendor\codeigniter4\framework\system\Database\BaseConnection.php(620): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `au...')
#3 C:\xampp\htdocs\tugas_akhir\vendor\codeigniter4\framework\system\Database\BaseBuilder.php(1916): CodeIgniter\Database\BaseConnection->query('INSERT INTO `au...', Array, false)
#4 C:\xampp\htdocs\tugas_akhir\app\Controllers\Admin.php(87): CodeIgniter\Database\BaseBuilder->insert(Array)
#5 C:\xampp\htdocs\tugas_akhir\vendor\codeigniter4\framework\system\CodeIgniter.php(902): App\Controllers\Admin->save()
#6 C:\xampp\htdocs\tugas_akhir\vendor\codeigniter4\framework\system\CodeIgniter.php(457): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Admin))
#7 C:\xampp\htdocs\tugas_akhir\vendor\codeigniter4\framework\system\CodeIgniter.php(340): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#8 C:\xampp\htdocs\tugas_akhir\public\index.php(67): CodeIgniter\CodeIgniter->run()
#9 C:\xampp\htdocs\tugas_akhir\vendor\codeigniter4\framework\system\Commands\Server\rewrite.php(46): require_once('C:\\xampp\\htdocs...')
#10 {main}
CRITICAL - 2022-12-03 12:48:04 --> Cannot add or update a child row: a foreign key constraint fails (`tugas_akhir`.`auth_groups_users`, CONSTRAINT `auth_groups_users_user_id_foreign` FOREIGN KEY (`user_id`) REFERENCES `users` (`id`) ON DELETE CASCADE ON UPDATE CASCADE)
in SYSTEMPATH\Database\MySQLi\Connection.php on line 292.
 1 SYSTEMPATH\Database\MySQLi\Connection.php(292): mysqli->query('INSERT INTO `auth_groups_users` (`group_id`, `user_id`) VALUES (2, \'users.id\')', 0)
 2 SYSTEMPATH\Database\BaseConnection.php(693): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `auth_groups_users` (`group_id`, `user_id`) VALUES (2, \'users.id\')')
 3 SYSTEMPATH\Database\BaseConnection.php(620): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `auth_groups_users` (`group_id`, `user_id`) VALUES (2, \'users.id\')')
 4 SYSTEMPATH\Database\BaseBuilder.php(1916): CodeIgniter\Database\BaseConnection->query('INSERT INTO `auth_groups_users` (`group_id`, `user_id`) VALUES (:group_id:, :user_id:)', [...], false)
 5 APPPATH\Controllers\Admin.php(87): CodeIgniter\Database\BaseBuilder->insert([...])
 6 SYSTEMPATH\CodeIgniter.php(902): App\Controllers\Admin->save()
 7 SYSTEMPATH\CodeIgniter.php(457): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Admin))
 8 SYSTEMPATH\CodeIgniter.php(340): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 9 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
10 SYSTEMPATH\Commands\Server\rewrite.php(46): require_once('FCPATH\\index.php')
ERROR - 2022-12-03 12:55:48 --> mysqli_sql_exception: Cannot add or update a child row: a foreign key constraint fails (`tugas_akhir`.`auth_groups_users`, CONSTRAINT `auth_groups_users_user_id_foreign` FOREIGN KEY (`user_id`) REFERENCES `users` (`id`) ON DELETE CASCADE ON UPDATE CASCADE) in C:\xampp\htdocs\tugas_akhir\vendor\codeigniter4\framework\system\Database\MySQLi\Connection.php:292
Stack trace:
#0 C:\xampp\htdocs\tugas_akhir\vendor\codeigniter4\framework\system\Database\MySQLi\Connection.php(292): mysqli->query('INSERT INTO `au...', 0)
#1 C:\xampp\htdocs\tugas_akhir\vendor\codeigniter4\framework\system\Database\BaseConnection.php(693): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `au...')
#2 C:\xampp\htdocs\tugas_akhir\vendor\codeigniter4\framework\system\Database\BaseConnection.php(620): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `au...')
#3 C:\xampp\htdocs\tugas_akhir\vendor\codeigniter4\framework\system\Database\BaseBuilder.php(1916): CodeIgniter\Database\BaseConnection->query('INSERT INTO `au...', Array, false)
#4 C:\xampp\htdocs\tugas_akhir\app\Controllers\Admin.php(87): CodeIgniter\Database\BaseBuilder->insert(Array)
#5 C:\xampp\htdocs\tugas_akhir\vendor\codeigniter4\framework\system\CodeIgniter.php(902): App\Controllers\Admin->save()
#6 C:\xampp\htdocs\tugas_akhir\vendor\codeigniter4\framework\system\CodeIgniter.php(457): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Admin))
#7 C:\xampp\htdocs\tugas_akhir\vendor\codeigniter4\framework\system\CodeIgniter.php(340): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#8 C:\xampp\htdocs\tugas_akhir\public\index.php(67): CodeIgniter\CodeIgniter->run()
#9 C:\xampp\htdocs\tugas_akhir\vendor\codeigniter4\framework\system\Commands\Server\rewrite.php(46): require_once('C:\\xampp\\htdocs...')
#10 {main}
CRITICAL - 2022-12-03 12:55:48 --> Cannot add or update a child row: a foreign key constraint fails (`tugas_akhir`.`auth_groups_users`, CONSTRAINT `auth_groups_users_user_id_foreign` FOREIGN KEY (`user_id`) REFERENCES `users` (`id`) ON DELETE CASCADE ON UPDATE CASCADE)
in SYSTEMPATH\Database\MySQLi\Connection.php on line 292.
 1 SYSTEMPATH\Database\MySQLi\Connection.php(292): mysqli->query('INSERT INTO `auth_groups_users` (`group_id`, `user_id`) VALUES (2, \'users.id\')', 0)
 2 SYSTEMPATH\Database\BaseConnection.php(693): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `auth_groups_users` (`group_id`, `user_id`) VALUES (2, \'users.id\')')
 3 SYSTEMPATH\Database\BaseConnection.php(620): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `auth_groups_users` (`group_id`, `user_id`) VALUES (2, \'users.id\')')
 4 SYSTEMPATH\Database\BaseBuilder.php(1916): CodeIgniter\Database\BaseConnection->query('INSERT INTO `auth_groups_users` (`group_id`, `user_id`) VALUES (:group_id:, :user_id:)', [...], false)
 5 APPPATH\Controllers\Admin.php(87): CodeIgniter\Database\BaseBuilder->insert([...])
 6 SYSTEMPATH\CodeIgniter.php(902): App\Controllers\Admin->save()
 7 SYSTEMPATH\CodeIgniter.php(457): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Admin))
 8 SYSTEMPATH\CodeIgniter.php(340): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 9 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
10 SYSTEMPATH\Commands\Server\rewrite.php(46): require_once('FCPATH\\index.php')
ERROR - 2022-12-03 12:56:27 --> mysqli_sql_exception: Unknown column 'group_id' in 'field list' in C:\xampp\htdocs\tugas_akhir\vendor\codeigniter4\framework\system\Database\MySQLi\Connection.php:292
Stack trace:
#0 C:\xampp\htdocs\tugas_akhir\vendor\codeigniter4\framework\system\Database\MySQLi\Connection.php(292): mysqli->query('INSERT INTO `us...', 0)
#1 C:\xampp\htdocs\tugas_akhir\vendor\codeigniter4\framework\system\Database\BaseConnection.php(693): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `us...')
#2 C:\xampp\htdocs\tugas_akhir\vendor\codeigniter4\framework\system\Database\BaseConnection.php(620): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `us...')
#3 C:\xampp\htdocs\tugas_akhir\vendor\codeigniter4\framework\system\Database\BaseBuilder.php(1916): CodeIgniter\Database\BaseConnection->query('INSERT INTO `us...', Array, false)
#4 C:\xampp\htdocs\tugas_akhir\app\Controllers\Admin.php(87): CodeIgniter\Database\BaseBuilder->insert(Array)
#5 C:\xampp\htdocs\tugas_akhir\vendor\codeigniter4\framework\system\CodeIgniter.php(902): App\Controllers\Admin->save()
#6 C:\xampp\htdocs\tugas_akhir\vendor\codeigniter4\framework\system\CodeIgniter.php(457): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Admin))
#7 C:\xampp\htdocs\tugas_akhir\vendor\codeigniter4\framework\system\CodeIgniter.php(340): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#8 C:\xampp\htdocs\tugas_akhir\public\index.php(67): CodeIgniter\CodeIgniter->run()
#9 C:\xampp\htdocs\tugas_akhir\vendor\codeigniter4\framework\system\Commands\Server\rewrite.php(46): require_once('C:\\xampp\\htdocs...')
#10 {main}
CRITICAL - 2022-12-03 12:56:27 --> Unknown column 'group_id' in 'field list'
in SYSTEMPATH\Database\MySQLi\Connection.php on line 292.
 1 SYSTEMPATH\Database\MySQLi\Connection.php(292): mysqli->query('INSERT INTO `users` (`group_id`, `user_id`) VALUES (2, \'users.id\')', 0)
 2 SYSTEMPATH\Database\BaseConnection.php(693): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `users` (`group_id`, `user_id`) VALUES (2, \'users.id\')')
 3 SYSTEMPATH\Database\BaseConnection.php(620): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `users` (`group_id`, `user_id`) VALUES (2, \'users.id\')')
 4 SYSTEMPATH\Database\BaseBuilder.php(1916): CodeIgniter\Database\BaseConnection->query('INSERT INTO `users` (`group_id`, `user_id`) VALUES (:group_id:, :user_id:)', [...], false)
 5 APPPATH\Controllers\Admin.php(87): CodeIgniter\Database\BaseBuilder->insert([...])
 6 SYSTEMPATH\CodeIgniter.php(902): App\Controllers\Admin->save()
 7 SYSTEMPATH\CodeIgniter.php(457): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Admin))
 8 SYSTEMPATH\CodeIgniter.php(340): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 9 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
10 SYSTEMPATH\Commands\Server\rewrite.php(46): require_once('FCPATH\\index.php')
CRITICAL - 2022-12-03 13:29:33 --> Argument 1 passed to CodeIgniter\Database\BaseBuilder::get() must be of the type int or null, string given, called in C:\xampp\htdocs\tugas_akhir\app\Controllers\Admin.php on line 80
in SYSTEMPATH\Database\BaseBuilder.php on line 1577.
 1 APPPATH\Controllers\Admin.php(80): CodeIgniter\Database\BaseBuilder->get('id')
 2 SYSTEMPATH\CodeIgniter.php(902): App\Controllers\Admin->save()
 3 SYSTEMPATH\CodeIgniter.php(457): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Admin))
 4 SYSTEMPATH\CodeIgniter.php(340): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 5 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
 6 SYSTEMPATH\Commands\Server\rewrite.php(46): require_once('FCPATH\\index.php')
CRITICAL - 2022-12-03 13:29:47 --> Undefined property: CodeIgniter\Database\MySQLi\Builder::$request
in APPPATH\Controllers\Admin.php on line 80.
 1 APPPATH\Controllers\Admin.php(80): CodeIgniter\Debug\Exceptions->errorHandler(8, 'Undefined property: CodeIgniter\\Database\\MySQLi\\Builder::$request', 'APPPATH\\Controllers\\Admin.php', 80, [...])
 2 SYSTEMPATH\CodeIgniter.php(902): App\Controllers\Admin->save()
 3 SYSTEMPATH\CodeIgniter.php(457): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Admin))
 4 SYSTEMPATH\CodeIgniter.php(340): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 5 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
 6 SYSTEMPATH\Commands\Server\rewrite.php(46): require_once('FCPATH\\index.php')
ERROR - 2022-12-03 15:39:49 --> mysqli_sql_exception: Unknown column 'id' in 'where clause' in C:\xampp\htdocs\tugas_akhir\vendor\codeigniter4\framework\system\Database\MySQLi\Connection.php:292
Stack trace:
#0 C:\xampp\htdocs\tugas_akhir\vendor\codeigniter4\framework\system\Database\MySQLi\Connection.php(292): mysqli->query('SELECT `nama_ka...', 0)
#1 C:\xampp\htdocs\tugas_akhir\vendor\codeigniter4\framework\system\Database\BaseConnection.php(693): CodeIgniter\Database\MySQLi\Connection->execute('SELECT `nama_ka...')
#2 C:\xampp\htdocs\tugas_akhir\vendor\codeigniter4\framework\system\Database\BaseConnection.php(620): CodeIgniter\Database\BaseConnection->simpleQuery('SELECT `nama_ka...')
#3 C:\xampp\htdocs\tugas_akhir\vendor\codeigniter4\framework\system\Database\BaseBuilder.php(1585): CodeIgniter\Database\BaseConnection->query('SELECT `nama_ka...', Array, false)
#4 C:\xampp\htdocs\tugas_akhir\app\Controllers\Admin.php(66): CodeIgniter\Database\BaseBuilder->get()
#5 C:\xampp\htdocs\tugas_akhir\vendor\codeigniter4\framework\system\CodeIgniter.php(902): App\Controllers\Admin->save()
#6 C:\xampp\htdocs\tugas_akhir\vendor\codeigniter4\framework\system\CodeIgniter.php(457): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Admin))
#7 C:\xampp\htdocs\tugas_akhir\vendor\codeigniter4\framework\system\CodeIgniter.php(340): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#8 C:\xampp\htdocs\tugas_akhir\public\index.php(67): CodeIgniter\CodeIgniter->run()
#9 C:\xampp\htdocs\tugas_akhir\vendor\codeigniter4\framework\system\Commands\Server\rewrite.php(46): require_once('C:\\xampp\\htdocs...')
#10 {main}
CRITICAL - 2022-12-03 15:39:49 --> Unknown column 'id' in 'where clause'
in SYSTEMPATH\Database\MySQLi\Connection.php on line 292.
 1 SYSTEMPATH\Database\MySQLi\Connection.php(292): mysqli->query('SELECT `nama_kamar`
FROM `kamar_santri`
WHERE `id` IS NULL', 0)
 2 SYSTEMPATH\Database\BaseConnection.php(693): CodeIgniter\Database\MySQLi\Connection->execute('SELECT `nama_kamar`
FROM `kamar_santri`
WHERE `id` IS NULL')
 3 SYSTEMPATH\Database\BaseConnection.php(620): CodeIgniter\Database\BaseConnection->simpleQuery('SELECT `nama_kamar`
FROM `kamar_santri`
WHERE `id` IS NULL')
 4 SYSTEMPATH\Database\BaseBuilder.php(1585): CodeIgniter\Database\BaseConnection->query('SELECT `nama_kamar`
FROM `kamar_santri`
WHERE `id` IS NULL', [], false)
 5 APPPATH\Controllers\Admin.php(66): CodeIgniter\Database\BaseBuilder->get()
 6 SYSTEMPATH\CodeIgniter.php(902): App\Controllers\Admin->save()
 7 SYSTEMPATH\CodeIgniter.php(457): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Admin))
 8 SYSTEMPATH\CodeIgniter.php(340): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 9 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
10 SYSTEMPATH\Commands\Server\rewrite.php(46): require_once('FCPATH\\index.php')
ERROR - 2022-12-03 20:43:34 --> mysqli_sql_exception: Unknown column 'nama_kamar' in 'field list' in C:\xampp\htdocs\tugas_akhir\vendor\codeigniter4\framework\system\Database\MySQLi\Connection.php:292
Stack trace:
#0 C:\xampp\htdocs\tugas_akhir\vendor\codeigniter4\framework\system\Database\MySQLi\Connection.php(292): mysqli->query('SELECT `users`....', 0)
#1 C:\xampp\htdocs\tugas_akhir\vendor\codeigniter4\framework\system\Database\BaseConnection.php(693): CodeIgniter\Database\MySQLi\Connection->execute('SELECT `users`....')
#2 C:\xampp\htdocs\tugas_akhir\vendor\codeigniter4\framework\system\Database\BaseConnection.php(620): CodeIgniter\Database\BaseConnection->simpleQuery('SELECT `users`....')
#3 C:\xampp\htdocs\tugas_akhir\vendor\codeigniter4\framework\system\Database\BaseBuilder.php(1585): CodeIgniter\Database\BaseConnection->query('SELECT `users`....', Array, false)
#4 C:\xampp\htdocs\tugas_akhir\app\Controllers\Admin.php(32): CodeIgniter\Database\BaseBuilder->get()
#5 C:\xampp\htdocs\tugas_akhir\vendor\codeigniter4\framework\system\CodeIgniter.php(902): App\Controllers\Admin->data_santri()
#6 C:\xampp\htdocs\tugas_akhir\vendor\codeigniter4\framework\system\CodeIgniter.php(457): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Admin))
#7 C:\xampp\htdocs\tugas_akhir\vendor\codeigniter4\framework\system\CodeIgniter.php(340): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#8 C:\xampp\htdocs\tugas_akhir\public\index.php(67): CodeIgniter\CodeIgniter->run()
#9 C:\xampp\htdocs\tugas_akhir\vendor\codeigniter4\framework\system\Commands\Server\rewrite.php(46): require_once('C:\\xampp\\htdocs...')
#10 {main}
CRITICAL - 2022-12-03 20:43:34 --> Unknown column 'nama_kamar' in 'field list'
in SYSTEMPATH\Database\MySQLi\Connection.php on line 292.
 1 SYSTEMPATH\Database\MySQLi\Connection.php(292): mysqli->query('SELECT `users`.`id` as `userid`, `username`, `fullname`, `email`, `user_image`, `jk`, `no_telp`, `wali`, `no_wali`, `thn_masuk`, `kamar`, `nama_kamar`
FROM `users`
JOIN `auth_groups_users` ON `auth_groups_users`.`user_id` = `users`.`id`
JOIN `auth_groups` ON `auth_groups`.`id` = `auth_groups_users`.`group_id`
WHERE `auth_groups`.`id` = (2)', 0)
 2 SYSTEMPATH\Database\BaseConnection.php(693): CodeIgniter\Database\MySQLi\Connection->execute('SELECT `users`.`id` as `userid`, `username`, `fullname`, `email`, `user_image`, `jk`, `no_telp`, `wali`, `no_wali`, `thn_masuk`, `kamar`, `nama_kamar`
FROM `users`
JOIN `auth_groups_users` ON `auth_groups_users`.`user_id` = `users`.`id`
JOIN `auth_groups` ON `auth_groups`.`id` = `auth_groups_users`.`group_id`
WHERE `auth_groups`.`id` = (2)')
 3 SYSTEMPATH\Database\BaseConnection.php(620): CodeIgniter\Database\BaseConnection->simpleQuery('SELECT `users`.`id` as `userid`, `username`, `fullname`, `email`, `user_image`, `jk`, `no_telp`, `wali`, `no_wali`, `thn_masuk`, `kamar`, `nama_kamar`
FROM `users`
JOIN `auth_groups_users` ON `auth_groups_users`.`user_id` = `users`.`id`
JOIN `auth_groups` ON `auth_groups`.`id` = `auth_groups_users`.`group_id`
WHERE `auth_groups`.`id` = (2)')
 4 SYSTEMPATH\Database\BaseBuilder.php(1585): CodeIgniter\Database\BaseConnection->query('SELECT `users`.`id` as `userid`, `username`, `fullname`, `email`, `user_image`, `jk`, `no_telp`, `wali`, `no_wali`, `thn_masuk`, `kamar`, `nama_kamar`
FROM `users`
JOIN `auth_groups_users` ON `auth_groups_users`.`user_id` = `users`.`id`
JOIN `auth_groups` ON `auth_groups`.`id` = `auth_groups_users`.`group_id`
WHERE `auth_groups`.`id` = :auth_groups.id:', [...], false)
 5 APPPATH\Controllers\Admin.php(32): CodeIgniter\Database\BaseBuilder->get()
 6 SYSTEMPATH\CodeIgniter.php(902): App\Controllers\Admin->data_santri()
 7 SYSTEMPATH\CodeIgniter.php(457): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Admin))
 8 SYSTEMPATH\CodeIgniter.php(340): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 9 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
10 SYSTEMPATH\Commands\Server\rewrite.php(46): require_once('FCPATH\\index.php')
